### ISSUE TITLE
Lack of grommunio-meet packages / broken meet service setup?

### ISSUE THREAD

**Issue by mika** [grammm-dev/grammm-cui#3]
Note: Sorry if I chose the wrong repository for reporting this, but I couldn't find a better repository.

1. Where are the projects/repositories for grommunio-meet or jitsi-meet?
2. Where should such issues be reported in the future?

We did a fresh installation of Grommunio v2021.08.3 (using https://download.grommunio.com/appliance/grommunio_Appliance.x86_64-2021.08.3-Build3.1.install.iso), with the `meet` feature enabled. But our system ended up without a working meet service.

In `/var/log/grommunio-setup.log` we noticed:

```
No provider of 'grommunio-jicofo' found.
'grommunio-meet' not found in package names. Trying capabilities.
No provider of 'grommunio-meet' found.
'grommunio-videobridge' not found in package names. Trying capabilities.
No provider of 'grommunio-videobridge' found.
```

Looking at https://download.grommunio.com/community/openSUSE_Leap_15.3/, there exist `jitsi-meet` + `jitsi-meet-branding-grommunio` packages though, sounds like a package rename which isn't covered by the installer.

Furthermore, after manually installing the `jitsi-meet jitsi-meet-branding-grommunio jitsi-meet-prosody-plugins` packages, we still ended up without a working meet service (`$URL/meet` just 404-ing).

Looking further, the jitsi-meet package ships a `/etc/nginx/vhosts.d/jitsi-meet.conf` file:

```
localhost:/etc/nginx # grep ssl /etc/nginx/vhosts.d/jitsi-meet.conf
    listen 0.0.0.0:443 ssl http2;
    listen [::]:443 ssl http2;
    #ssl_certificate /var/lib/prosody/localhost.crt;
    #ssl_certificate_key /var/lib/prosody/localhost.key;
    ssl_certificate /etc/nginx/ssl/localhost.with.chain.pem;
    ssl_certificate_key /etc/nginx/ssl/localhost.with.chain.pem;
```

The SSL certificate files don't exist on the system, so this had to be adjusted. But shouldn't this be `/etc/grommunio-common/ssl/server-bundle.pem` + `/etc/grommunio-common/ssl/server.key` by default instead, that could be covered by `grommunio-setup`?

After fixing the `ssl_certificate{,_key}` configs, the service didn't work either. It seems like `/usr/share/grommunio-common/nginx.conf` and `/etc/nginx/vhosts.d/jitsi-meet.conf` conflict with each other, and actually a `/usr/share/grommunio-common/nginx/locations.d/grommunio-meet.conf` is supposed to be provided instead? Though no such file seems to be available, isn't this also something to be covered by `grommunio-setup`?

How is this supposed to be working, how to get (jitsi) meet working in grommunio?

**Comment by grammmike** [comment]
Thanks or your report, and sorry for just stopping by. grommunio-cui is actually not really the right place for this report. For everything install related, maybe checkout https://community.grommunio.com/

Last but not least: The packages in question have been renamed and with the latest version of grommunio (2022.05.1), the new packages are leveraged with jitsi-meet* - Tanks for your report!
