### ISSUE TITLE
get_last_login_time: last_login referenced before assignment

### ISSUE THREAD

**Issue by crpb** [grammm-dev/grammm-cui#8]
https://github.com/grommunio/grommunio-cui/blob/dcebcfee7d395dc7cfffe6f0b9f00fe33adcd7a2/cui/util.py#L548-L565

if you add a `last_login=""` before try-block it will not [fail](https://community.grommunio.com/d/1452-endlosschleife-beim-start-des-grommunio-console-user-interface-nach-update).
Thats because the splitlines doesn't work in all cases i presume and no OSerror will be thrown.

With an command like `last -1 --time-format iso --hostlast root |awk {print$3;quit}` you might get around it.

**Comment by jengelh** [comment]
72a463acd70eb3cfc2ba208fee03f91482044850
